<a href="https://colab.research.google.com/github/pedrohenrique792/ML2023-PedroHenrique/blob/main/C%C3%B3pia_de_3_Tipos_e_Convers%C3%A3o_de_tipos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

![datatypes.png](attachment:datatypes.png)

Importa a biblioteca numpy

In [2]:
import numpy as np

Cria uma variável q recebe um atributo do tipo float32 com valor 1.0

In [3]:
x = np.float32(1.0)
x

1.0

Cria uma variável q recebe um array como atributo do tipo inteiro

In [4]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

Cria um array com 3 elementos com os atributos do tipo uint8

In [5]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

Cria um array do tipo float32

In [6]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

Converte o array z para float

In [7]:
z.astype(float)

array([0., 1., 2.])

Converte o array z para int8

In [8]:
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

Verifica qual o tipo do arry

In [10]:
z.dtype

dtype('uint8')