<a href="https://colab.research.google.com/github/pedrohenrique792/ML2023-PedroHenrique/blob/main/C%C3%B3pia_de_7_Filtragem_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 7 - Filtragem de dados
Filtragem de dados é uma tarefa importantíssima na vida de qualquer cientista de dados. Nessa seção, veremos como criar filtros em um conjunto de dados utilizando o Pandas.

## Operadores booleanos

### and

Adicionou o valor "12" a variável x

In [1]:
x = 12

Fez uma comparação usando o opereando "and" à variável x 

In [11]:
x > 5 and x < 15

True

### or

Adicionou o valor "12" a variável x

In [3]:
y = 5

Fez uma comparação usando o opereando "or" à variável y 

In [4]:
y < 7 or y > 13

True

### not

Usou o operando not para negar o booleano TRUE

In [5]:
not True

False

Usou o operando not para negar o booleano FALSE

In [6]:
not False

True

### Numpy



1.   Importou a biblioteca numpy
2.   Criou o array np_height para armazenar alturas
3.   Criou o array np_height para armazenar pesos
4.   Criou o array bmi para armazenar o resultado do imc



In [12]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

Retorna o booleano dos imc que são maiores que 21

In [13]:
bmi > 21

array([ True, False,  True,  True,  True])

Retorna um booleano para indicar se todos os valores estão dentro do intervalo das condições propostas

In [16]:
#bmi > 21 and bmi < 22
bmi.all() > 21 and  bmi.all() < 22

False

Retorna um booleano para indicar os valores que estão dentro do intervalo das condições propostas

In [17]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

Retorna os valores estão dentro do intervalo das condições propostas

In [18]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

## Filtrando um DataFrame Pandas



1.   Importa a biblioteca pandas
2.   Importa um dataframe a partir do arquivo "brics.csv"



In [21]:
import pandas as pd
brics = pd.read_csv('brics.csv', index_col=0)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

**Objetivo**: selecionar os países com área maior do que 8 milhões de km2

3 passos:
- Selecionar a coluna "area"
- Fazer uma comparação na coluna "area"
- Usar o resultado para selecionar os países

Seleciona a coluna "area"

In [22]:
# Selecionar a coluna "area"
brics['area']

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

Faz uma comparação na coluna "area"

In [23]:
# Fazer uma comparação na coluna "area"
brics['area'] > 8
is_huge = brics['area'] > 8
is_huge

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

Usa o resultado para selecionar os países desejados

In [25]:
# Usar o resultado para selecionar os países
brics[is_huge]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0



1.   Importa a biblioteca pandas
2.   Importa um dataframe a partir do arquivo "cars.csv"



In [26]:
# Importando dataset de carros
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
cars

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True



1.   Selecionou os carros que possuiam a coluna drives_right = TRUE e salvou na variável "dr"
2.   Criou o subconjunto "sel" para armazenar os dados da variável "dr"
3.   Imprimiu "sel"



In [27]:
# Extraia a coluna 'drives_right' do DataFrame 'cars' e atribua a variável 'dr'
dr = cars['drives_right']

# Use a variável 'dr' para criar um subconjunto de dados chamado 'sel'
sel = cars[dr]

# Imprima a variável 'sel'
print(sel)

     cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True




1.   Selecionou os carros que possuiam a coluna cars_per_cap = TRUE e salvou na variável "cpc"
2.   Criou a variável "many_cars" para selecionar os carros que possuem cpc > 500
3.   Criou o subconjunto "car_maniac" para armazenar os dados da variável "many_cars"
4.   Imprimiu "car_maniac"



In [28]:
# Crie uma variável car_maniac: linhas que possuem 'cars_per_cap' maiores do que 500
cpc = cars['cars_per_cap']
many_cars = cpc > 500
car_maniac = cars[many_cars]

# Imprima 'car_maniac'
print(car_maniac)

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False




1.   Importa a biblioteca pandas
2.   Importa a biblioteca numpy
3.   Cria a variável cars para armazenar os dados do arquivo "cars.csv"
4.   Selecionou os carros que possuiam a coluna cars_per_cap = TRUE e salvou na variável "cpc"
5.   Criou a variável "between" para selecionar os carros que possuem cpc > 100 e cpc < 500
3.   Criou o subconjunto "medium" para armazenar os dados da variável "between"
4.   Imprimiu "medium"







In [30]:
# Importe o conjunto de dados 'cars.csv', bem como as bibliotecas 'pandas' e 'numpy'
import pandas as pd
import numpy as np
cars = pd.read_csv('cars.csv', index_col = 0)

# Crie a variável 'medium': linhas que possuem 'cars_per_cap' entre 100 e 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]

# Imprima 'medium'
print(medium)

    cars_per_cap country  drives_right
RU           200  Russia          True
